/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PrimeChecker */

#ifndef _Included_PrimeChecker
#define _Included_PrimeChecker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PrimeChecker
 * Method:    isPrime
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_PrimeChecker_isPrime
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
